---

- name: Install the openldap and required Packages for RedHat
  package:
    name={{ item }}
    state=latest
  with_items: "{{ openldap_server_pkgs }}"

# - name: Delete the configuration directory
#   file:
#     path={{ openldap_server_app_path }}/slapd.d
#     state=absent

- name: Generate OpenLDAP admin password
  shell: slappasswd -s {{ openldap_server_rootpw }}
  register: root_password

- name: Copy file for OpenLDAP admin password
  template:
    src={{ openldap_chroot_template }}.jinja2
    dest={{ openldap_config_files_folder }}/{{ openldap_chroot_template }}

- name: Set OpenLDAP admin password
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f {{ openldap_config_files_folder }}/{{ openldap_chroot_template }}
  notify:
    - restart slapd

- fail:

- name: Copy the slapd.conf configuration file
  template:
    src={{ openldap_ldap_conf_template }}
    dest={{ openldap_server_app_path }}/slapd.conf
  notify:
   - restart slapd

- name: Copy the ldap.conf configuration file
  template:
    src=ldap.conf.j2
    dest={{ openldap_server_app_path }}/ldap.conf
