openldap_server_pkgs:
  - slapd
  - ldap-utils
  - python-selinux
  - openssl

openldap_ldap_conf_template: "slapd.conf_ubuntu.j2"
openldap_server_app_path: "/etc/ldap/"
openldap_server_user: "openldap"
