galaxy_info:
  author: Adrian G Prado
  description: Install and setup nfs-client

  license: MIT

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
    - system

dependencies: []
