---
# Centos 7 instructions
#  https://www.server-world.info/en/note?os=CentOS_7&p=nfs&f=1

# 0 include OS variables
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# 1 install necessary packages
- name: Install nfs-server needed packages
  package:
    name="{{ item }}"
    state=latest
  with_items: "{{ nfs_server_pkgs }}"

# 2 Configure files
- name: Set nfs-server domain name
  lineinfile:
    dest=/etc/idmapd.conf
    regexp="^#Domain = local.domain.edu$"
    line="Domain = {{ nfs_server }}"

- name: Ensure directories to export exist
  file:
    path="{{ item.server }}"
    state=directory
    mode=777
  with_items: "{{ nfs_exports }}"

- name: Restart and enable services
  service:
    name="{{ item }}"
    state=restarted
    enabled=yes
  with_items: "{{ nfs_server_services }}"

- name: Write NFS exports
  template:
    src=exports.j2
    dest=/etc/exports
    owner=root
    group=root
    mode=0777
  notify:
    - restart nfs-server
    - restart rpcbind

- name: Start firewalld service
  service:
    name=firewalld
    state=restarted
    enabled=yes

# firewall-cmd --permanent --zone=public --add-service=nfs
- name: Allow NFS service on firewall
  firewalld:
    service=nfs
    state=enabled
    zone=public
    permanent=true
  notify:
    - restart firewall
    - restart nfs-server
    - restart rpcbind
