---
# Centos 7 instructions
#  https://www.server-world.info/en/note?os=CentOS_7&p=nfs&f=1

# 0 include OS variables
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# 1 install necessary packages
- name: Install nfs-server needed packages
  package:
    name="{{ item }}"
    state=latest
  with_items: "{{ nfs_server_pkgs }}"

# 2 Configure files
- name: Set nfs-server domain name
  lineinfile:
    dest=/etc/idmapd.conf
    regexp='^#Domain = local.domain.edu$'
    line='Domain = {{ nfs_server_FQDN }}'

- name: Ensure directories to export exist
  file:
    path="{{ item.split(' ')[0]}}"
    state=directory
  with_items: "{{ nfs_exports }}"
  notify:
    - restart nfs
    - restart rpcbind

- name: Write NFS exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: nfs_exports_copy
  notify:
    - restart nfs
    - restart rpcbind

- name: Allow NFS service on firewall
  firewalld:
    service=https
    state=enabled
    permanent=true
  notify:
    - restart firewall
    - restart nfs
    - restart rpcbind
