---
- hosts: all
  become: yes
  vars:
    - public_iface: "{{ ansible_default_ipv4.interface }}"
  tasks:
    - name: build /etc/hosts file
      lineinfile:
        dest=/etc/hosts
        regexp='.*{{ item }}$'
        line="{{ hostvars[item].ansible_host }} {{item}}"
        state=present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups['all']}}"
